trigger:
  branches:
    include:
      - main

pool:
  name: Forlarhh2
  vmImage: 'ubuntu-latest'

variables:
  - group: VaultCredentials
  - name: VAULT_ADDR
    value: $(VAULT_ADDR)

steps:
  # Step 1: Install HashiCorp Vault CLI
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Installing Vault CLI..."
        curl -O https://releases.hashicorp.com/vault/1.10.0/vault_1.10.0_linux_amd64.zip
        unzip vault_1.10.0_linux_amd64.zip
        sudo mv vault /usr/local/bin/
        vault --version
    displayName: 'Install Vault CLI'

  # Step 2: Install Terraform CLI
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'
    displayName: 'Install Terraform'

  # Step 3: Authenticate with Vault using AppRole
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Authenticating to Vault using AppRole..."
        vault login -method=approle role_id=$(VAULT_ROLE_ID) secret_id=$(VAULT_SECRET_ID) -format=json > login-output.json
        export VAULT_TOKEN=$(cat login-output.json | jq -r ".auth.client_token")
        echo "##vso[task.setvariable variable=VAULT_TOKEN]$VAULT_TOKEN"
    env:
      VAULT_ADDR: $(VAULT_ADDR)
      VAULT_ROLE_ID: $(VAULT_ROLE_ID)
      VAULT_SECRET_ID: $(VAULT_SECRET_ID)
    displayName: 'Authenticate to Vault'

  # Step 4: Initialize and Apply Terraform
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Initializing and Applying Terraform..."
        
        # Set Azure credentials in environment variables from Vault
        export ARM_CLIENT_ID=$(vault kv get -field=value secret/data/azure/client_id)
        export ARM_CLIENT_SECRET=$(vault kv get -field=value secret/data/azure/client_secret)
        export ARM_SUBSCRIPTION_ID=$(vault kv get -field=value secret/data/azure/subscription_id)
        export ARM_TENANT_ID=$(vault kv get -field=value secret/data/azure/tenant_id)
        
        # Initialize and apply Terraform
        terraform init
        terraform apply -auto-approve
    env:
      VAULT_TOKEN: $(VAULT_TOKEN)
    displayName: 'Run Terraform'
