name: Fetch Vault Secrets and Trigger Azure Pipeline

on:
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Vault CLI
        run: |
          curl -L -o vault.zip https://releases.hashicorp.com/vault/1.10.4/vault_1.10.4_linux_amd64.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/
      
      - name: Authenticate to Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          echo "Authenticating to Vault..."
          echo $VAULT_TOKEN | vault login -

      - name: Retrieve Secrets from Vault
        id: vault_secrets
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          export VAULT_SECRET_PATH="secret/data/azure"
          SECRET_DATA=$(vault kv get -field=data -format=json $VAULT_SECRET_PATH)
          echo "::set-output name=secrets::$SECRET_DATA"

      - name: Convert Secrets to GitHub Environment Variables
        run: |
          echo "Extracting Vault secrets..."
          echo "${{ steps.vault_secrets.outputs.secrets }}" > secrets.json
          AZURE_SECRET1=$(jq -r '.azure_secret1' secrets.json)
          AZURE_SECRET2=$(jq -r '.azure_secret2' secrets.json)
          echo "::set-env name=AZURE_SECRET1::$AZURE_SECRET1"
          echo "::set-env name=AZURE_SECRET2::$AZURE_SECRET2"

      - name: Trigger Azure DevOps Pipeline with Secrets
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PIPELINE_ID: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          echo "Triggering Azure DevOps pipeline..."
          curl -X POST \
            -u ":${AZURE_DEVOPS_PAT}" \
            -H "Content-Type: application/json" \
            -d '{
                  "resources": {
                    "repositories": {
                      "self": {
                        "refName": "refs/heads/main"
                      }
                    }
                  },
                  "variables": {
                    "AZURE_SECRET1": {
                      "value": "'$AZURE_SECRET1'"
                    },
                    "AZURE_SECRET2": {
                      "value": "'$AZURE_SECRET2'"
                    }
                  }
                }' \
            "$AZURE_DEVOPS_ORG_URL/$AZURE_DEVOPS_PROJECT/_apis/pipelines/$AZURE_DEVOPS_PIPELINE_ID/runs?api-version=6.0-preview.1"
