name: Vault Change Detection and Azure Pipeline Trigger

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_vault_and_trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install vault -y

    - name: Start Vault in Dev Mode
      env:
        VAULT_DEV_ROOT_TOKEN_ID: ${{ secrets.VAULT_DEV_ROOT_TOKEN_ID }}  # Set your fixed root token here
      run: |
        nohup vault server -dev -dev-root-token-id="$VAULT_DEV_ROOT_TOKEN_ID" > vault.log 2>&1 &
        sleep 5  # Give Vault some time to start

    - name: Write Dummy Data to Vault
      env:
        VAULT_ADDR: 'http://127.0.0.1:8200'
        VAULT_TOKEN: ${{ secrets.VAULT_DEV_ROOT_TOKEN_ID }}
      run: |
        vault kv put secret/my-secret foo=bar

    - name: Set Environment Variables
      run: |
        echo "VAULT_ADDR=http://127.0.0.1:8200" >> $GITHUB_ENV
        echo "VAULT_TOKEN=${{ secrets.VAULT_DEV_ROOT_TOKEN_ID }}" >> $GITHUB_ENV

    - name: Cache Vault Data Hash
      id: cache_hash
      uses: actions/cache@v3
      with:
        path: .vault_data_hash
        key: vault-data-hash

    - name: Check Vault for Changes
      id: check_vault
      run: |
        NEW_HASH=$(vault kv get -mount="secret" -format=json my-secret | jq -r '.data')
        if [ -f ".vault_data_hash" ]; then
          OLD_HASH=$(cat .vault_data_hash)
        else
          OLD_HASH=""
        fi
        if [ "$NEW_HASH" != "$OLD_HASH" ]; then
          echo "Vault data has changed."
          echo "$NEW_HASH" > .vault_data_hash
          echo "has_changed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes in Vault data."
          echo "has_changed=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Trigger Azure DevOps Pipeline
      if: steps.check_vault.outputs.has_changed == 'true'
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        AZURE_DEVOPS_PIPELINE_ID: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
      run: |
       echo "Triggering Azure DevOps pipeline..."
       curl -X POST "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/pipelines/${AZURE_DEVOPS_PIPELINE_ID}/runs?api-version=6.0-preview" \
       -H "Content-Type: application/json" \
       -u :$AZURE_DEVOPS_TOKEN \
       -d '{}'

    - name: Output Vault Logs on Failure
      if: failure()
      run: |
        echo "Vault CLI output:"
        cat vault.log
