name: Vault Change Detection and Azure Pipeline Trigger

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_vault_and_trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install vault -y

    - name: Start Vault in Docker
      run: |
        docker run --cap-add=IPC_LOCK -d --name vault \
          -e 'VAULT_DEV_ROOT_TOKEN_ID=root' \
          -e 'VAULT_DISABLE_MLOCK=true' \
          vault:1.11.3 server -dev \
          -dev-root-token-id=root \
          -dev-listen-address="0.0.0.0:8201"

    - name: Wait for Vault to be ready
      run: |
        until docker exec vault vault status >/dev/null 2>&1; do
          echo "Waiting for Vault..."
          sleep 2
        done
        echo "Vault is ready."

    - name: Write Dummy Data to Vault
      run: |
        docker exec vault vault kv put secret/azure foo=bar

    - name: Check Vault for Changes
      id: check_vault
      run: |
        NEW_HASH=$(docker exec vault vault kv get -format=json secret/azure | jq -r '.data')
        
        # Read the previously stored hash if it exists
        if [ -f ".vault_data_hash" ]; then
          OLD_HASH=$(cat .vault_data_hash)
        else
          OLD_HASH=""
        fi

        # Check if the hash has changed
        if [ "$NEW_HASH" != "$OLD_HASH" ]; then
          echo "Vault data has changed."
          echo "$NEW_HASH" > .vault_data_hash
          echo "has_changed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes in Vault data."
          echo "has_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Trigger Azure DevOps Pipeline
      if: steps.check_vault.outputs.has_changed == 'true'
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        AZURE_DEVOPS_PIPELINE_ID: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
      run: |
        echo "Triggering Azure DevOps pipeline..."
        
        # Trigger the pipeline
        curl -X POST "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/pipelines/${AZURE_DEVOPS_PIPELINE_ID}/runs?api-version=6.0-preview" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AZURE_DEVOPS_TOKEN" \
          -d '{}'

    - name: Check Docker Containers
      run: |
        docker ps -a

    - name: Vault Container Logs
      if: failure()
      run: |
        echo "Dumping Vault container logs due to failure:"
        docker logs vault
