name: Vault Change Detection and Azure Pipeline Trigger

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_vault_and_trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install vault -y

    - name: Check Vault for Changes
      id: check_vault
      env:
        VAULT_ADDR: 'http://127.0.0.1:8201'
        VAULT_TOKEN: 'hvs.CAESIOZoYzFk3EZoALiUZ6fQQvzev7-7WLHNAGYe5VDnEtKFGh4KHGh2cy5sVG1EVmVpTmlTSlVVNk1mWXBtMWlwaEM'
      run: |
        
        NEW_HASH=$(vault kv get -field=data -format=json secret/data/azure | jq -r '.data')
        
        # Read the previously stored hash if it exists
        if [ -f ".vault_data_hash" ]; then
          OLD_HASH=$(cat .vault_data_hash)
        else
          OLD_HASH=""
        fi

        # Check if the hash has changed
        if [ "$NEW_HASH" != "$OLD_HASH" ]; then
          echo "Vault data has changed."
          echo "$NEW_HASH" > .vault_data_hash
          echo "::set-output name=has_changed::true"
        else
          echo "No changes in Vault data."
          echo "::set-output name=has_changed::false"
        fi

    - name: Trigger Azure DevOps Pipeline
      if: steps.check_vault.outputs.has_changed == 'true'
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        AZURE_DEVOPS_PIPELINE_ID: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
      run: |
        echo "Triggering Azure DevOps pipeline..."
        
        # Trigger the pipeline
        curl -X POST "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/pipelines/${AZURE_DEVOPS_PIPELINE_ID}/runs?api-version=6.0-preview" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AZURE_DEVOPS_TOKEN" \
          -d '{}'
