name: Sync Vault Secrets to Azure DevOps

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Enables manual triggering in the GitHub Actions UI

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install hvac requests

      - name: Run Check Secrets Script
        id: check_secrets
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          source venv/bin/activate
          python check_secrets.py

      - name: Trigger Azure DevOps Pipeline
        if: steps.check_secrets.outputs.trigger == 'true'
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          organization='Forlarhh'
          project='Vault'
          pipeline_id='4'
          url="https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline_id/runs?api-version=6.0-preview.1"
          
          # Trigger the Azure DevOps pipeline
          curl -X POST -H "Authorization: Basic $(echo ":$AZURE_DEVOPS_PAT" | base64)" $url
          echo "Pipeline triggered successfully!"
