name: Vault Change Detection and Azure Pipeline Trigger

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_vault_and_trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Install Vault CLI
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install vault -y

    - name: Start Vault Server in Dev Mode
      run: |
        nohup vault server -dev -dev-root-token-id="root" -dev-listen-address="127.0.0.1:8201" > vault.log 2>&1 &

    - name: Wait for Vault to be ready
      run: |
        for i in {1..10}; do
          if vault status >/dev/null 2>&1; then
            echo "Vault is ready."
            exit 0
          else
            echo "Waiting for Vault..."
            sleep 2
          fi
        done
        echo "Vault failed to start."
        exit 1

    - name: Write Dummy Data to Vault
      env:
        VAULT_ADDR: 'http://127.0.0.1:8201'
        VAULT_TOKEN: 'root'
      run: |
        vault kv put secret/azure foo=bar

    - name: Check Vault for Changes
      id: check_vault
      env:
        VAULT_ADDR: 'http://127.0.0.1:8201'
        VAULT_TOKEN: 'root'
      run: |
        NEW_HASH=$(vault kv get -format=json secret/azure | jq -r '.data')

        if [ -f ".vault_data_hash" ]; then
          OLD_HASH=$(cat .vault_data_hash)
        else
          OLD_HASH=""
        fi

        if [ "$NEW_HASH" != "$OLD_HASH" ]; then
          echo "Vault data has changed."
          echo "$NEW_HASH" > .vault_data_hash
          echo "has_changed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes in Vault data."
          echo "has_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Trigger Azure DevOps Pipeline
      if: steps.check_vault.outputs.has_changed == 'true'
      env:
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        AZURE_DEVOPS_PIPELINE_ID: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
      run: |
        echo "Triggering Azure DevOps pipeline..."
        curl -X POST "https://dev.azure.com/${AZURE_DEVOPS_ORG}/${AZURE_DEVOPS_PROJECT}/_apis/pipelines/${AZURE_DEVOPS_PIPELINE_ID}/runs?api-version=6.0-preview" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AZURE_DEVOPS_TOKEN" \
          -d '{}'

    - name: Output Vault Logs on Failure
      if: failure()
      run: |
        echo "Vault server logs:"
        cat vault.log
